### ISSUE TITLE
Gd is not installed

### ISSUE THREAD

**Issue by Nightbr** [thecodingmachine/kickoff-docker-php-images#1]
Hey, 
I found a small error in php-fpm image. 

## Expected Behavior
Gd should be installed

## Current Behavior
Gd is not installed:
` Fatal error: Uncaught Imagine\Exception\RuntimeException: Gd not installed`

## Possible Solution
https://github.com/thecodingmachine/kickoff-docker-php-images/blob/master/php-fpm/Dockerfile.blueprint#L42

Add Gd to the list of plugin install.

* Version used: v2.0.0-rc1
* Operating System and version: Linux Mint 18.2

Regards!

**Comment by gulien** [comment]
Hi @Nightbr!

Indeed, let me fix it :)

**Comment by gulien** [comment]
I've just released the [v2.0.0-rc2](https://github.com/thecodingmachine/kickoff-docker-php/releases/tag/v2.0.0-rc2) version of kickoff-docker-php!
I'm now using the rc2 images of this repository. And of course Gd is now correctly installed!

Thank you again!

**Comment by Nightbr** [comment]
Thanks for your amazing work! Loved the way you have set up all this stuff!
